import os
import uuid
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INVOICE_DIR = os.path.join(BASE_DIR, "invoices")
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").rstrip("/")

FONT_PATH = os.path.join(BASE_DIR, "fonts", "NotoSans-Regular.ttf")

if not os.path.exists(FONT_PATH):
    # Fallback to system font if local font is missing for some reason
    FONT_PATH = "/System/Library/Fonts/Supplemental/Arial Unicode.ttf"

pdfmetrics.registerFont(TTFont("InvoiceUnicode", FONT_PATH))

os.makedirs(INVOICE_DIR, exist_ok=True)


def generate_invoice(
    business_name: str,
    customer_name: str,
    items: list,
    gst_percent: float = 0,
    discount: float = 0,
):
    invoice_number = f"INV-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
    invoice_date = datetime.now().strftime("%d/%m/%Y")

    subtotal = sum(
        float(item["quantity"]) * float(item["price"])
        for item in items
    )

    gst_amount = subtotal * (gst_percent / 100)
    total_before_discount = subtotal + gst_amount
    total = max(0, total_before_discount - discount)

    filename = f"{invoice_number}.pdf"
    filepath = os.path.join(INVOICE_DIR, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "InvoiceTitle",
        parent=styles["Title"],
        fontSize=24,
        spaceAfter=8,
        fontName="InvoiceUnicode",
    )

    normal_style = ParagraphStyle(
        "NormalInvoice",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        fontName="InvoiceUnicode",
    )

    story = []

    story.append(Paragraph("INVOICE", title_style))
    story.append(Paragraph(f"<b>{business_name}</b>", normal_style))
    story.append(Spacer(1, 8))

    invoice_info = [
        ["Invoice Number", invoice_number],
        ["Invoice Date", invoice_date],
        ["Customer", customer_name],
    ]

    info_table = Table(invoice_info, colWidths=[45 * mm, 100 * mm])

    info_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "InvoiceUnicode"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    story.append(info_table)
    story.append(Spacer(1, 15))

    table_data = [
        ["Item", "Qty", "Price", "Amount"]
    ]

    for item in items:
        quantity = float(item["quantity"])
        price = float(item["price"])
        amount = quantity * price

        table_data.append(
            [
                str(item["name"]),
                str(item["quantity"]),
                f"Rs. {price:.2f}",
                f"Rs. {amount:.2f}",
            ]
        )

    table_data.extend(
        [
            ["", "", "Subtotal", f"Rs. {subtotal:.2f}"],
            ["", "", f"GST ({gst_percent}%)", f"Rs. {gst_amount:.2f}"],
            ["", "", "Discount", f"-Rs. {discount:.2f}"],
            ["", "", "TOTAL", f"Rs. {total:.2f}"],
        ]
    )

    invoice_table = Table(
        table_data,
        colWidths=[80 * mm, 20 * mm, 35 * mm, 35 * mm],
    )

    invoice_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "InvoiceUnicode"),
                ("FONTNAME", (0, -4), (-1, -1), "InvoiceUnicode"),
                ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
                ("GRID", (0, 0), (-1, -5), 0.5, colors.grey),
                ("LINEABOVE", (2, -4), (-1, -4), 0.5, colors.grey),
                ("LINEABOVE", (2, -1), (-1, -1), 1, colors.black),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )

    story.append(invoice_table)
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Thank you for your business!<br/>"
            "Generated by MSMEAssist AI",
            normal_style,
        )
    )

    doc.build(story)

    invoice_public_url = None
    if PUBLIC_BASE_URL:
        invoice_public_url = f"{PUBLIC_BASE_URL}/invoices/{filename}"

    return {
        "success": True,
        "invoice_number": invoice_number,
        "filename": filename,
        "filepath": filepath,
        "invoice_url": filepath,
        "invoice_public_url": invoice_public_url,
        "total": round(total, 2),
    }